### ISSUE TITLE
Library failed to load

### ISSUE THREAD

**Issue by sesemina** [igordot/clustermole#1]
Hi!
I use to use this package for a long time and everything worked fine till now. 
> library(clustermole)
Error: package or namespace load failed for ‘clustermole’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘matrixStats’ 0.59.0 is already loaded, but >= 0.60.0 is required
In addition: Warning message:
package ‘clustermole’ was built under R version 4.1.1

Can you help to solve the problem?

**Comment by igordot** [comment]
It looks like your package versions are somehow out of sync. Can you try updating matrixStats?

**Comment by sesemina** [comment]
Yes, it worked. Thank you!
