### ISSUE TITLE
Reference paper

### ISSUE THREAD

**Issue by bashhike** [igordot/clustermole#2]
Hi Igor, 

Thank you for this wonderful piece of software, it's really helpful and has made my life much easier. 
I was wondering if there is a reference paper published detailing the methodologies used in this package, if there is I would love to go through it.

**Comment by igordot** [comment]
I am glad to hear you found it useful. I assume you are referring to methodologies implemented in `clustermole_enrichment()`. The options are ssGSEA (Barbie et al, 2009), GSVA (Hänzelmann et al, 2013), and singscore (Foroutan et al, 2018). You can check the function docs for full references.
