### ISSUE TITLE
Meaning of xCell cell type abbreviations. 

### ISSUE THREAD

**Issue by jcorn427** [igordot/clustermole#3]
Hi Igor, first off, your software is amazing and has helped me classify a PBMC dataset from golden hamsters. I do have a question though. Included in the xCell dataset care cell types with these labels: CMP_BLUEPRINT_1, and MEP_BLUEPRINT_1. I've been trying to find what CMP and MEP stand for, both through xCell and the blueprint project and have not found an answer yet. Any help would be much appreciated.

**Comment by jcorn427** [comment]
Actually, I think I just figured it out. Thanks though!

**Comment by igordot** [comment]
In case anyone else has the same question in the future, these are just various hematopoietic progenitor populations, such as the Common Myeloid Progenitor (CMP) or the Megakaryocyte-Erythroid Progenitor (MEP). Here is a nice representation [[source](https://www.nature.com/articles/nri3062/figures/1)]:
![41577_2011_Article_BFnri3062_Fig1_HTML](https://user-images.githubusercontent.com/6363505/180025600-7b3038e4-adb1-47ff-bbc0-62b5371d5cea.jpeg)
