### ISSUE TITLE
List of genes for each cell type

### ISSUE THREAD

**Issue by jcorn427** [igordot/clustermole#4]
Hello, I was wondering, would I be able to get a list of the genes that clustermole finds for of the cell types listed? For example, under n_genes it might say 7, but those genes aren't listed anywhere.

**Comment by igordot** [comment]
Apologies about the extremely delayed response. Somehow I forgot to respond. In case you are still interested, the data frame returned by `clustermole_markers()` includes the genes in the `gene` column.
